### ISSUE TITLE
Yelp API call has some Node version incompatibilities. 

### ISSUE THREAD

**Issue by jamespeeler** [jamespeeler/LGBTQ-Acceptance-Rating#17]
If Node version is older than version 18, you _must_ define 'fetch' in the server.js file, or the server won't run.
If Node version is version 18 or newer, you _cannot_ define 'fetch' in the server.js file, or the server won't run.

We need a way for the server to run regardless of which Node version someone is using, preferably programmatically.

**Comment by michaeljoelt** [comment]
I read that "console.log(process.version)" should print the version of node running. so maybe can use process.version in an if statement to see if its under 18, and define fetch when that's true

**Comment by jamespeeler** [comment]
For version control right now, I think we're just going to go the route of: Make sure anyone using the app has the supported version of Node installed (v18). 

So for now, I'm going to close this issue, and if we decide later to support earlier versions of Node, we can cross that bridge at that point.
