### ISSUE TITLE
New HTML file

### ISSUE THREAD

**Issue by jamespeeler** [jamespeeler/LGBTQ-Acceptance-Rating#2]
We need an HTML file for our project. 

From Amy- on Discord:
For the .html, we could have like.
A input with a button
And then two like paragraphs/headers with the score/name of the company?

**Comment by ApplePieAngel** [comment]
The HTML we have is a good start, some ideas I have:
1. What about having a working business as a default value for the input?
2. And changing the name of the button could be good as well!
3. We can also experiment with adding more stats, etc.

**Comment by gabrielarce** [comment]
Hey Team, 

sorry for getting back so late.  I see some of y'all got started on the HTML doc.  Thank you for getting that started on that.  I have added on top of the index.html file.  Can someone remind me how I add my contribution? I think i'm supposed to do a pull request, but i'm not 100% sure what i'm supposed to do?

**Comment by ApplePieAngel** [comment]
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request

Does this documentation help any? If you need more specific help with any errors, let me know and we can try walking through it together.

**Comment by jamespeeler** [comment]
> 

You'll need to first push your code to your fork, the same exact way you do codewars. Then you can go to https://github.com/jamespeeler/rainbow-group-project/pulls and click "Pull request" in the top right, it'll show you a page comparing the main branch to your branch. Make sure to add comments as to what you're adding, then submit the pull request. Then, either one of us can merge your request, or you can do it yourself by clicking the "merge" button on the pull requests page.

The documentation that Amy has in their comment has a lot of good info. That along with the bottom of this site: 
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
should get you fully up to speed.

**Comment by michaeljoelt** [comment]
ideas here have been implemented, and will create more specific issues for further needs.
