### ISSUE TITLE
Frontend - JS - display random rating to page

### ISSUE THREAD

**Issue by michaeljoelt** [jamespeeler/LGBTQ-Acceptance-Rating#23]
(main.js)

Every time the makeReq function is called, a random rating should be displayed to the page. you can use/repurpose variable randomRating for this. 

the html element the rating should be displayed through has an id of "businessRating"

**Comment by jamespeeler** [comment]
~~For some reason it isn't letting me assign @daniellemaxwell to this issue. They worked on and completed this issue, so I'll leave their @ in this comment and close out the issue.~~

Fixed the problem and appropriately assigned Danielle to the issue.
