### ISSUE TITLE
Rename project? 

### ISSUE THREAD

**Issue by michaeljoelt** [jamespeeler/LGBTQ-Acceptance-Rating#36]
I haven't looked in to what this process involves, but it seems like it might be beneficial to rename this project to help others find it who may want to contribute down the line. Maybe something like "LGBTQ-Acceptance-Rating"?

Might also be beneficial to look in to tagging the project (if possible) with key words that can help people search for it too.

**Comment by jamespeeler** [comment]
Whoa!!! I'm so sorry for the late reply to this, I didn't see this issue get added. I will look into changing the repo name right away.

**Comment by jamespeeler** [comment]
And done! The repo has been renamed to "LGBTQ-Acceptance-Rating". You won't need to do anything on your end, GitHub will automatically redirect your code to the new repo name when you push it.
