### ISSUE TITLE
New server.js file

### ISSUE THREAD

**Issue by jamespeeler** [jamespeeler/LGBTQ-Acceptance-Rating#4]
We need the server.js file to connect our client frontend code to the server backend

**Comment by michaeljoelt** [comment]
updated server code to allow for querying businesses (so far only one business is hard-coded in). suggested next steps for server:
- update Business class - add a property to the Business class called "sources". it can be an array of strings, specifically urls that lead to reasons for the rating.
- make query request more dynamic -  for example: create an array of Business objects. when handling the "business" query request, check if the query string matches one of the business names in the array. this should allow us to more easily create and search through a lot more businesses

**Comment by ApplePieAngel** [comment]
I've updated the server code to create an array of Business object as per your specifications. When making a request, it checks to see if it matches one of the business names in the array and pulls from that if it does. If it doesn't, it creates it and pushes it to the end of the array. 

It still needs refactoring, such as moving/remove initial hard coded logic. As well as none of the data is uploaded or saved into any database, so it'll be deleted after every reset.

**Comment by michaeljoelt** [comment]
ideas here were implemented; and the yelp api has now replaced the need for our hardcoded businesses and business class. new issues will be created for more specific server needs.
