### ISSUE TITLE
New CSS file

### ISSUE THREAD

**Issue by jamespeeler** [jamespeeler/LGBTQ-Acceptance-Rating#5]
We need some CSS!!! We want to make our site beautiful and rainbow themed!

**Comment by ApplePieAngel** [comment]
Some ideas I have in mind: 
1. Everything is centered / or aligned the way you think looks nice.
2. LGBTQ+ themed colors!
3. What if all images were a fixed size? And stretch/contains depending on size.
4. Whatever else you think would be good. Get creative and experiment with stuff even if you think its not going to be amazing!

**Comment by michaeljoelt** [comment]
CSS file has been updated with ideas described here. creating new issues on further, more specific needs.
